### ISSUE TITLE
When a student answers an answered question, they still get the points.

### ISSUE THREAD

**Issue by larryyueli** [quizzard-edu/quizzard#160]
They should be able to answer the questions again, but they shouldn't get the points anymore.

**Comment by Mohammed-JS-Khan** [comment]
The backend prevents the points from getting added, so there is no issue there. Im wokring on revamping that notification entirely right now, so hopefully by tonight I will merge that. This issue will be fixed in that merge.

If a student answers a question again they get a message that just says "Congratulations you got the question right!" instead of the normal message.

**Comment by larryyueli** [comment]
But what I saw was that my total points displayed actually increased every time I answered the same question. The number stays after the refresh, so something got updated at the backend.

**Comment by Mohammed-JS-Khan** [comment]
@larryyueli interesting. I think @mehtadarshan1 or @ahmedqarmout2 are looking into the backend issues with that.

**Comment by Mohammed-JS-Khan** [comment]
The UI part of this issue will be fixed with PR #162 but the backend work still remains.
