### ISSUE TITLE
Updating Leaderboards 

### ISSUE THREAD

**Issue by Mohamed-A-Mohamed** [quizzard-edu/quizzard#83]
Multiple leader boards for different achievements such as highest amount of points, highest question answer acurracy, over all best student, etc.

**Comment by esteeroramy** [comment]
After lots of thought in designing this, here is a step by step process of how things could look like. This design ensures minimal data upload and download in order to minimize the load on the user, the server, and the database. Attached is a visual of how things may look like.
1. The user selects the leaderboard page, this makes a call to server.js in order to change the page the user is viewing to become the leaderboard page.
2. We now make a request from 'leaderboard.js` (the component) to `server.js` (the API). This will request the leaderboard
3. `server.js` (the API) will call `users.js` (the Backend) asking to get the data
4. `users.js` (the backend) will call `db.js` (the database) to get the information of the students'
5. `users.js` will receive the list of users with a lot of data
6. `users.js` will use the data given to calculate all the statistics needed and return only the usernames followed by the criteria for each leaderboard type, make sure that there is no extra data sent back to ensure efficiency
7. `server.js` (the API) will then receive this data and will not modify it
8. `server.js` (the API) will render the outline of the table. The outline of the table is basically the whole table without any elements inside of it. The section in which the elements will go should be clearly defined using a unique I'd that we will use later on. 
9. `server.js` (the API) will ALSO render a single row of the table. The single row of the table should be in its own `.pug` (template) file. This is going to ensure this approach to be dynamic. This single row is going to be just a table entry formatted correctly to fit the data that is needed. In this entry we should make sure that we have unique ids where we are expecting to put data, such as name, rank, and criteria of the sort
10. Now `server.js` (the API) is ready to return the data. So it will return the data that it for from `users.js` (the backend) which has the information of all the studemts, it will also return the `HTML` rendered outline of the table, and ONLY ONE `HTML`  rendered table entry.
11. `leaderboard.js` (the component) will receive this data and will place the table outline on the correct place, then figure out which sort is selected.
12. Once the sort type is selected, `leaderboard.js` (the component) will call a sorting function that should be dynamic to accept any sort of the criteria. This should use a globally defined list in `common.js`
13. Once the sort is done, a `binding` function should be called. This function will bind the sorted data to a list of `HTML` rows, using the `HTML` that was returned to us of the table entry from `server.js` (the API)
14. Once the binding is done, we are then ready to use `JQuery` to populate the table outline with the binded rows.

This is a lot of work. Please ask me if there is anything that is unclear or does not make sense. Ahmed and I would be happy to help :)
NOTE: the steps listed are not the exact same as the picture, they are written in more detail
![img_20171117_171459_01](https://user-images.githubusercontent.com/28266659/32972149-bb77e7e4-cbbe-11e7-9cf6-d8465b357966.jpg)
